// default package
// Generated 2015-12-28 22:48:12 by Hibernate Tools 3.4.0.CR1
package com.ordersystem.domain;
import java.util.HashSet;
import java.util.Set;

/**
 * Employees generated by hbm2java
 */
public class Employees implements java.io.Serializable {

	private int employeeNumber;
	private Offices offices;
	private Employees employees;
	private String lastName;
	private String firstName;
	private String extension;
	private String email;
	private String jobTitle;
	private Set employeeses = new HashSet(0);
	private Set customerses = new HashSet(0);

	public Employees() {
	}

	public Employees(int employeeNumber, Offices offices, String lastName,
			String firstName, String extension, String email, String jobTitle) {
		this.employeeNumber = employeeNumber;
		this.offices = offices;
		this.lastName = lastName;
		this.firstName = firstName;
		this.extension = extension;
		this.email = email;
		this.jobTitle = jobTitle;
	}

	public Employees(int employeeNumber, Offices offices, Employees employees,
			String lastName, String firstName, String extension, String email,
			String jobTitle, Set employeeses, Set customerses) {
		this.employeeNumber = employeeNumber;
		this.offices = offices;
		this.employees = employees;
		this.lastName = lastName;
		this.firstName = firstName;
		this.extension = extension;
		this.email = email;
		this.jobTitle = jobTitle;
		this.employeeses = employeeses;
		this.customerses = customerses;
	}

	public int getEmployeeNumber() {
		return this.employeeNumber;
	}

	public void setEmployeeNumber(int employeeNumber) {
		this.employeeNumber = employeeNumber;
	}

	public Offices getOffices() {
		return this.offices;
	}

	public void setOffices(Offices offices) {
		this.offices = offices;
	}

	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	public Set getEmployeeses() {
		return this.employeeses;
	}

	public void setEmployeeses(Set employeeses) {
		this.employeeses = employeeses;
	}

	public Set getCustomerses() {
		return this.customerses;
	}

	public void setCustomerses(Set customerses) {
		this.customerses = customerses;
	}

}
