// default package
// Generated 2015-12-28 22:48:12 by Hibernate Tools 3.4.0.CR1
package com.ordersystem.domain;
import java.util.Date;

/**
 * Payments generated by hbm2java
 */
public class Payments implements java.io.Serializable {

	private PaymentsId id;
	private Customers customers;
	private Date paymentDate;
	private double amount;

	public Payments() {
	}

	public Payments(PaymentsId id, Customers customers, Date paymentDate,
			double amount) {
		this.id = id;
		this.customers = customers;
		this.paymentDate = paymentDate;
		this.amount = amount;
	}

	public PaymentsId getId() {
		return this.id;
	}

	public void setId(PaymentsId id) {
		this.id = id;
	}

	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

}
